name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Lint & Format
        run: |
          npm run lint
          npm run format:check
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Prepare Database (push schema + seed)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
        run: |
          npx prisma db push
          npm run db:seed --if-present
      - name: Run E2E
        env:
          NEXTAUTH_URL: http://localhost:3000
          AUTH_SECRET: testsecret
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
          TEST_AUTH_SECRET: dev
        run: |
          npm run test:e2e -- --reporter=dot
