name: Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-database:
    runs-on: ubuntu-latest
    outputs:
      db-accessible: ${{ steps.check.outputs.accessible }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Check Database Connectivity
        id: check
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Try to connect to database
          npx prisma db execute --schema ./prisma/schema.prisma --stdin <<< "SELECT 1;" || {
            echo "accessible=false" >> $GITHUB_OUTPUT
            echo "::warning::Database not accessible from GitHub Actions. Migrations should be run locally."
            exit 0
          }
          echo "accessible=true" >> $GITHUB_OUTPUT
        continue-on-error: true
        working-directory: .

  migrate:
    needs: check-database
    if: needs.check-database.outputs.db-accessible == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: .

      - name: Run migrations (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
        working-directory: .

  notify-manual-migration:
    needs: check-database
    if: needs.check-database.outputs.db-accessible != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Migration Notice
        run: |
          echo "::notice::Database migrations need to be run manually."
          echo "Run locally: npm run db:migrate"
