name: Migrate DB

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: dbt-diary-card

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: dbt-diary-card

      - name: Run migrations (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
        working-directory: dbt-diary-card
